service: jeffpay
provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  timeout: 30
  environment:
    TZ: Asia/Tokyo
    USER_TABLE:
      Ref: UserTable
    WALLET_TABLE:
      Ref: WalletTable
    PAYMENT_HISTORY_TABLE:
      Ref: PaymentHistoryTable
    NOTIFICATION_ENDPOINT: "https://dkxmaha7zk.execute-api.us-west-2.amazonaws.com/prod/notification"
    LOCATION_ENDPOINT: "https://dkxmaha7zk.execute-api.us-west-2.amazonaws.com/prod/location"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - "*"

functions:
  CreateUser:
    handler: user_create.user_create
    events:
      - http:
          path: users
          method: post
  WalletCharge:
    handler: wallet_charge.wallet_charge
    events:
      - http:
          path: wallet/charge
          method: post
  WalletUse:
    handler: wallet_use.wallet_use
    events:
      - http:
          path: wallet/use
          method: post
  WalletTransfer:
    handler: wallet_transfer.wallet_transfer
    events:
      - http:
          path: wallet/transfer
          method: post
  GetUserSummary:
    handler: get_user_summary.get_user_summary
    events:
      - http:
          path: users/{userId}/summary
          method: get
  GetPaymentHistory:
    handler: get_payment_history.get_payment_history
    events:
      - http:
          path: users/{userId}/history
          method: get

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    WalletTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    PaymentHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: walletId
            AttributeType: S
          - AttributeName: transactionId
            AttributeType: S
        KeySchema:
          - AttributeName: walletId
            KeyType: HASH
          - AttributeName: transactionId
            KeyType: RANGE
